namespace: webapp

deployment:
  image: "weighttrackerapp.azurecr.io/webapp"
  tag: "$(build.BuildId"
  replicas: 4

ingress:
  name: ingress

configmap:
  host: 0.0.0.0
  port: 80
  host_url: http://192.168.100.11
  node_env: development
  cookie_pwd: superAwesomePasswordStringThatIsAtLeast32CharactersLong!
  okta_id: 0oa5armrmeQjQY6lH5d7
  okta_secret: OFcEZa-YPwGuAQ6m77NJPVPE8dFZy4h_M9wZm43S
  okta_url: https://dev-66078042.okta.com
  pg_db: postgres
  pg_host: To be filled when cluster & db are up
  pg_pwd: To be filled when cluster & db are up
  pg_port: 5432
  pg_username: postgres